import 'package:flutter/widgets.dart';

// Static method to get AppLocalizations from context
AppLocalizations of(BuildContext context) {
  // Try to get locale from Localizations or fallback to 'it'
  Locale? localeObj = Localizations.maybeLocaleOf(context);
  String locale = localeObj?.languageCode ?? 'it';
  return AppLocalizations(locale);
}

// Simple localization class for EN/ITA, easily extendable
class AppLocalizations {
  // Static method to get AppLocalizations from context
  static AppLocalizations of(BuildContext context) {
    Locale localeObj;
    try {
      localeObj = Localizations.localeOf(context);
    } catch (_) {
      localeObj = const Locale('it');
    }
    String locale = localeObj.languageCode;
    return AppLocalizations(locale);
  }

  final String locale;
  AppLocalizations(this.locale);

  static const supportedLocales = ['en', 'it'];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings_flag_secure_desc': 'Prevents screenshots and screen recording',
      'settings_flag_secure_title': 'Secure screen',
      'select_currency': 'Select currency',
      'select_period_hint_short': 'Set dates',
      'select_period_hint': 'Select a date range',
      'save_change_expense': 'Save changes',
      'group_total': 'Total',
      'download_all_csv': 'Download all (CSV)',
      'share_all_csv': 'Share all (CSV)',
      'welcome_v3_title': 'Organize.\nShare.\nSettle.\n ',
      // Saluti dinamici
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'your_groups': 'Your groups',
      'no_active_groups': 'No active groups',
      'no_active_groups_subtitle':
          'Create your first expense group to get started',
      'create_first_group': 'Create first group',

      'new_expense_group': 'New Expense Group',
      'tap_to_create': 'Tap to create',
      'no_expense_label': 'No expenses found',
      'image': 'Image',
      'select_image': 'Select Image',
      'change_image': 'Change Image',
      'from_gallery': 'From Gallery',
      'from_camera': 'From Camera',
      'remove_image': 'Remove Image',

      'no_trips_found': 'Where do you want to go?',
      'expenses': 'Expenses',
      'participants': 'Participants',
      'participants_label': 'Participants',
      'last_7_days': '7 days',
      'recent_activity': 'Recent activity',
      'about': 'About',
      'license_hint': 'This app is released under the MIT license.',
      'license_link': 'View MIT License on GitHub',
      'license_section': 'License',
      'add_trip': 'Add group',
      'new_group': 'New Group',
      'group_name': 'Name',
      'enter_title': 'Enter a name',
      'enter_participant': 'Enter at least one participant',
      'select_start': 'Select start',
      'select_end': 'Select end',
      'start_date_not_selected': 'Select start',
      'end_date_not_selected': 'Select end',
      'select_from_date': 'Select from',
      'select_to_date': 'Select to',
      'date_range_not_selected': 'Select period',
      'date_range_partial': 'Select both dates',
      'save': 'Save',
      'delete_trip': 'Delete trip',
      'delete_trip_confirm': 'Are you sure you want to delete this trip?',
      'cancel': 'Cancel',
      'ok': 'OK',
      'from_to': '{start} - {end}',
      'add_expense': 'New expense',
      'edit_expense': 'Edit expense',
      'category': 'Category',
      'amount': 'Amount',
      'invalid_amount': 'Invalid amount',
      'no_categories': 'No categories',
      'add_category': 'Add category',
      'category_name': 'Category name',
      'note': 'Note',
      'note_hint': 'Add a note (optional)',
      'select_both_dates': 'If you select one date, you must select both',
      'select_both_dates_or_none': 'Select both dates or leave both empty',
      'end_date_after_start': 'End date must be after start date',
      'start_date_optional': 'From',
      'end_date_optional': 'To',
      'dates': 'Period',
      'expenses_by_participant': 'By participant',
      'expenses_by_category': 'By category',
      'uncategorized': 'Uncategorized',
      'backup': 'Backup',
      'no_trips_to_backup': 'No trips to backup',
      'backup_error': 'Backup failed',
      'backup_share_message': 'Here is your Caravella backup',
      'import': 'Import',
      'import_confirm_title': 'Import data',
      'import_confirm_message':
          'Are you sure you want to overwrite all trips with the file "{file}"? This action cannot be undone.',
      'import_success': 'Import successful! Data reloaded.',
      'import_error': 'Import failed. Check the file format.',
      'categories': 'Categories',
      'from': 'From',
      'to': 'To',
      'add': 'Add',
      'participant_name': 'Participant name',
      'participant_name_hint': 'Enter participant name',
      'edit_participant': 'Edit participant',
      'delete_participant': 'Delete participant',
      'add_participant': 'Add participant',
      'no_participants': 'No participants',
      'category_name_hint': 'Enter category name',
      'edit_category': 'Edit category',
      'delete_category': 'Delete category',
      'participant_name_semantics': 'Participant: {name}',
      'category_name_semantics': 'Category: {name}',
      'currency': 'Currency',
      'settings_tab': 'Settings',
      'basic_info': 'Basic Information',
      'settings': 'Settings',
      'history': 'History',
      'all': 'ALL',
      'search_groups': 'Search groups...',
      'no_search_results': 'No groups found for',
      'try_different_search': 'Try searching with different words',
      'active': 'Active',
      'archived': 'Archived',
      'archive': 'Archive',
      'unarchive': 'Unarchive',
      'archive_confirm': 'Do you want to archive',
      'unarchive_confirm': 'Do you want to unarchive',
      'overview': 'Overview',
      'statistics': 'Statistics',
      'options': 'Options',
      'show_overview': 'Show overview',
      'show_statistics': 'Show statistics',
      'no_expenses_to_display': 'No expenses to display',
      'no_expenses_to_analyze': 'No expenses to analyze',
      'select_expense_date': 'Select expense date',
      'select_expense_date_short': 'Select date',
      'date': 'Date',
      'edit_group': 'Edit Group',
      'delete_group': 'Delete group',
      'delete_group_confirm':
          'Are you sure you want to delete this expense group? This action cannot be undone.',
      'add_expense_fab': 'Add Expense',
      'pin_group': 'Pin group',
      'unpin_group': 'Unpin group',
      'theme_automatic': 'Automatic',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'developed_by': 'Developed by calca',
      'links': 'Links',
      'daily_expenses_chart': 'Daily expenses',
      'weekly_expenses_chart': 'Weekly expenses',
      'monthly_expenses_chart': 'Monthly expenses',
      'weekly_chart_badge': 'W',
      'monthly_chart_badge': 'M',
      'daily_average_by_category': 'Daily average by category',
      'daily_average': 'Daily average',
      'spent_today': 'Spent today',
      'per_day': '/day',
      'no_expenses_for_statistics': 'No expenses available for statistics',
      'settlement': 'Settlement',
      'all_balanced': 'All accounts are balanced!',
      'owes_to': ' owes ',
      // Export CSV
      'export_csv': 'Export CSV',
      'no_expenses_to_export': 'No expenses to export',
      'export_csv_share_text': 'Expenses exported from ',
      'export_csv_error': 'Error exporting expenses',
      'expense_name': 'Description',
      'paid_by': 'Paid by',
      'expense_added_success': 'Expense added',
      'expense_updated_success': 'Expense updated',
      'data_refreshing': 'Refreshing…',
      'data_refreshed': 'Updated',
      'refresh': 'Refresh',
      'group_added_success': 'Group added',
      // CSV save / picker messages
      'csv_select_directory_title': 'Select folder to save CSV',
      'csv_saved_in': 'CSV saved in: {path}',
      'csv_save_cancelled': 'Export cancelled',
      'csv_save_error': 'Error saving CSV file',
      // CSV column headers
      'csv_expense_name': 'Description',
      'csv_amount': 'Amount',
      'csv_paid_by': 'Paid by',
      'csv_category': 'Category',
      'csv_date': 'Date',
      'csv_note': 'Note',
      'csv_location': 'Location',
      'location': 'Location',
      'location_hint': 'Add location (optional)',
      'get_current_location': 'Use current location',
      'enter_location_manually': 'Enter manually',
      'location_permission_denied': 'Location permission denied',
      'location_service_disabled': 'Location service disabled',
      'getting_location': 'Getting location...',
      'location_error': 'Error getting location',
      'settings_general': 'General',
      'settings_language': 'Language',
      'settings_language_it': 'Italian',
      'settings_language_en': 'English',
      'settings_select_language': 'Select language',
      'settings_theme': 'Theme',
      'settings_select_theme': 'Select theme',
      'settings_data': 'Data',
      'settings_data_manage': 'Data management',
      'settings_data_desc': 'Backup and restore',
      'settings_info': 'Information',
      'settings_app_version': 'App version',
      'settings_info_card': 'Information',
      'settings_info_card_desc': 'Developer, Source code and License',
      'terms_github_title': 'GitHub: calca',
      'terms_github_desc': 'Developer profile on GitHub.',
      'terms_repo_title': 'GitHub Repository',
      'terms_repo_desc': 'Application source code.',
      'terms_issue_title': 'Report a problem',
      'terms_issue_desc': 'Go to the GitHub issues page.',
      'terms_license_desc': 'View the open source license.',
      'data_title': 'Backup & Restore',
      'data_backup_title': 'Backup',
      'data_backup_desc': 'Create a backup file of your expenses.',
      'data_restore_title': 'Restore',
      'data_restore_desc': 'Import a backup to restore your data.',
    },
    'it': {
      'settings_flag_secure_desc':
          'Impedisce screenshot e registrazione schermo',
      'settings_flag_secure_title': 'Proteggi schermata',
      'select_currency': 'Seleziona valuta',
      'select_period_hint_short': 'Imposta date',
      'select_period_hint': 'Seleziona un intervallo di date',
      'save_change_expense': 'Salva modifiche',
      'group_total': 'Totale',
      'download_all_csv': 'Scarica tutto (CSV)',
      'share_all_csv': 'Condividi tutto (CSV)',
      // Saluti dinamici
      'good_morning': 'Buongiorno',
      'good_afternoon': 'Buon pomeriggio',
      'good_evening': 'Buonasera',
      'your_groups': 'I tuoi gruppi',
      'no_active_groups': 'Nessun gruppo attivo',
      'no_active_groups_subtitle': 'Crea il primo gruppo di spese per iniziare',
      'create_first_group': 'Crea primo gruppo',

      'new_expense_group': 'Nuovo Gruppo di Spese',
      'tap_to_create': 'Tocca per creare',
      'no_expense_label': 'Nessuna spesa trovata',
      'image': 'Immagine',
      'select_image': 'Seleziona Immagine',
      'change_image': 'Cambia Immagine',
      'from_gallery': 'Dalla Galleria',
      'from_camera': 'Dalla Fotocamera',
      'remove_image': 'Rimuovi Immagine',

      'no_trips_found': 'Dove vuoi andare?',
      'expenses': 'Spese',
      'participants_label': 'Partecipanti',
      'participants': 'Partecipanti',
      'last_7_days': '7 giorni',
      'recent_activity': 'Attività recente',
      'about': 'Informazioni',
      'license_hint': 'Questa app è distribuita con licenza MIT.',
      'license_link': 'Visualizza licenza MIT',
      'license_section': 'Licenza',
      'add_trip': 'Aggiungi un gruppo',
      'new_group': 'Nuovo Gruppo',
      'group_name': 'Nome',
      'enter_title': 'Inserisci un nome',
      'enter_participant': 'Inserisci almeno un partecipante',
      'select_start': 'Seleziona inizio',
      'select_end': 'Seleziona fine',
      'start_date_not_selected': 'Seleziona inizio',
      'end_date_not_selected': 'Seleziona fine',
      'select_from_date': 'Seleziona inizio',
      'select_to_date': 'Seleziona fine',
      'date_range_not_selected': 'Seleziona periodo',
      'date_range_partial': 'Seleziona entrambe le date',
      'save': 'Salva',
      'delete_trip': 'Elimina viaggio',
      'delete_trip_confirm': 'Sei sicuro di voler eliminare questo viaggio?',
      'cancel': 'Annulla',
      'ok': 'OK',
      'from_to': '{start} - {end}',
      'add_expense': 'Nuova spesa',
      'edit_expense': 'Modifica spesa',
      'category': 'Categoria',
      'amount': 'Importo',
      'invalid_amount': 'Importo non valido',
      'no_categories': 'Nessuna categoria',
      'add_category': 'Aggiungi categoria',
      'category_name': 'Nome categoria',
      'note': 'Note',
      'note_hint': 'Aggiungi una nota (opzionale)',
      'select_both_dates': 'Se selezioni una data, devi selezionare entrambe',
      'select_both_dates_or_none':
          'Seleziona entrambe le date o lascia entrambe vuote',
      'end_date_after_start':
          'La data di fine deve essere successiva a quella di inizio',
      'start_date_optional': 'Dal',
      'end_date_optional': 'Al',
      'dates': 'Periodo',
      'expenses_by_participant': 'Per partecipante',
      'expenses_by_category': 'Per categoria',
      'uncategorized': 'Senza categoria',
      'backup': 'Backup',
      'no_trips_to_backup': 'Nessun viaggio da salvare',
      'backup_error': 'Backup non riuscito',
      'backup_share_message': 'Ecco il backup di Caravella',
      'import': 'Importa',
      'import_confirm_title': 'Importa dati',
      'import_confirm_message':
          'Sicuro di voler sovrascrivere tutti i viaggi con il file "{file}"? L’operazione non è reversibile.',
      'import_success': 'Import riuscito! Dati ricaricati.',
      'import_error': 'Import fallito. Controlla il formato del file.',
      'categories': 'Categorie',
      'from': 'Dal',
      'to': 'Al',
      'add': 'Aggiungi',
      'participant_name': 'Nome partecipante',
      'participant_name_hint': 'Inserisci il nome del partecipante',
      'edit_participant': 'Modifica partecipante',
      'delete_participant': 'Elimina partecipante',
      'add_participant': 'Aggiungi partecipante',
      'no_participants': 'Nessun partecipante',
      'category_name_hint': 'Inserisci il nome della categoria',
      'edit_category': 'Modifica categoria',
      'delete_category': 'Elimina categoria',
      'participant_name_semantics': 'Partecipante: {name}',
      'category_name_semantics': 'Categoria: {name}',
      'currency': 'Valuta',
      'settings_tab': 'Impostazioni',
      'basic_info': 'Informazioni di base',
      'settings': 'Impostazioni',
      'history': 'Cronologia',
      'all': 'TUTTI',
      'info_tab': 'Info',
      'select_paid_by': 'Seleziona chi ha pagato',
      'select_category': 'Seleziona una categoria',
      'check_form': 'Controlla i dati inseriti',
      'delete_expense': 'Elimina spesa',
      'delete_expense_confirm': 'Sei sicuro di voler eliminare questa spesa?',
      'delete': 'Elimina',
      'no_expenses_for_statistics':
          'Nessuna spesa disponibile per le statistiche',
      'daily_expenses_chart': 'Spese giornaliere',
      'weekly_expenses_chart': 'Spese settimanali',
      'monthly_expenses_chart': 'Spese mensili',
      'weekly_chart_badge': 'S',
      'monthly_chart_badge': 'M',
      'daily_average_by_category': 'Media giornaliera per categoria',
      'daily_average': 'Media giornaliera',
      'spent_today': 'Speso oggi',
      'per_day': '/giorno',
      'general_statistics': 'Statistiche generali',
      'average_expense': 'Spesa media',
      'settlement': 'Pareggia',
      'all_balanced': 'Tutti i conti sono pari!',
      'owes_to': ' deve dare a ',
      // Welcome section v3 - Clean design
      'welcome_v3_title': 'Organizza.\nCondividi.\nBilancia.\n ',
      'welcome_v3_cta': 'Inizia!',
      'active': 'Attivo',
      'archived': 'Archiviato',
      'archive': 'Archivia',
      'unarchive': 'Disarchivia',
      'archive_confirm': 'Vuoi archiviare',
      'unarchive_confirm': 'Vuoi disarchiviare',
      'overview': 'Panoramica',
      'statistics': 'Statistiche',
      'options': 'Opzioni',
      'show_overview': 'Mostra panoramica',
      'show_statistics': 'Mostra statistiche',
      'no_expenses_to_display': 'Nessuna spesa da visualizzare',
      'no_expenses_to_analyze': 'Nessuna spesa da analizzare',
      'select_expense_date': 'Seleziona data spesa',
      'select_expense_date_short': 'Seleziona data',
      'date': 'Data',
      'edit_group': 'Modifica gruppo',
      'delete_group': 'Elimina gruppo',
      'delete_group_confirm':
          'Sei sicuro di voler eliminare questo gruppo di spese? Questa azione non può essere annullata.',
      'add_expense_fab': 'Aggiungi Spesa',
      'pin_group': 'Aggiungi pin',
      'unpin_group': 'Rimuovi pin',
      'theme_automatic': 'Automatico',
      'theme_light': 'Chiaro',
      'theme_dark': 'Scuro',
      'developed_by': 'Sviluppato da calca',
      'links': 'Collegamenti',

      // Export CSV
      'export_csv': 'Esporta CSV',
      'no_expenses_to_export': 'Nessuna spesa da esportare',
      'export_csv_share_text': 'Spese esportate da ',
      'export_csv_error': 'Errore nell\'esportazione delle spese',
      'expense_name': 'Descrizione',
      'paid_by': 'Pagato da',
      'expense_added_success': 'Spesa aggiunta',
      'expense_updated_success': 'Spesa aggiornata',
      'data_refreshing': 'Aggiornamento…',
      'data_refreshed': 'Aggiornato',
      'refresh': 'Aggiorna',
      'group_added_success': 'Gruppo aggiunto',
      // Messaggi salvataggio CSV / selezione cartella
      'csv_select_directory_title': 'Seleziona cartella per salvare CSV',
      'csv_saved_in': 'CSV salvato in: {path}',
      'csv_save_cancelled': 'Esportazione annullata',
      'csv_save_error': 'Errore nel salvataggio del file CSV',
      // Intestazioni colonne CSV
      'csv_expense_name': 'Descrizione',
      'csv_amount': 'Importo',
      'csv_paid_by': 'Pagato da',
      'csv_category': 'Categoria',
      'csv_date': 'Data',
      'csv_note': 'Nota',
      'csv_location': 'Posizione',
      'location': 'Posizione',
      'location_hint': 'Aggiungi posizione (opzionale)',
      'get_current_location': 'Usa posizione corrente',
      'enter_location_manually': 'Inserisci manualmente',
      'location_permission_denied': 'Permesso posizione negato',
      'location_service_disabled': 'Servizio posizione disabilitato',
      'getting_location': 'Rilevamento posizione...',
      'location_error': 'Errore nel rilevare la posizione',
      'settings_general': 'Generali',
      'settings_language': 'Lingua',
      'settings_language_it': 'Italiano',
      'settings_language_en': 'Inglese',
      'settings_select_language': 'Seleziona lingua',
      'settings_theme': 'Tema',
      'settings_select_theme': 'Seleziona tema',
      'settings_data': 'Dati',
      'settings_data_manage': 'Gestione dati',
      'settings_data_desc': 'Backup e ripristino',
      'settings_info': 'Informazioni',
      'settings_app_version': 'Versione dell\'app',
      'settings_info_card': 'Informazioni',
      'settings_info_card_desc': 'Sviluppatore, Source code e Licenza',
      'terms_github_title': 'GitHub: calca',
      'terms_github_desc': 'Profilo dello sviluppatore su GitHub.',
      'terms_repo_title': 'Repository GitHub',
      'terms_repo_desc': 'Codice sorgente dell’applicazione.',
      'terms_issue_title': 'Segnala un problema',
      'terms_issue_desc': 'Vai alla pagina delle issue su GitHub.',
      'terms_license_desc': 'Visualizza la licenza open source.',
      'data_title': 'Backup & Ripristino',
      'data_backup_title': 'Backup',
      'data_backup_desc': 'Crea un file di backup delle tue spese.',
      'data_restore_title': 'Ripristino',
      'data_restore_desc': 'Importa un backup per ripristinare i dati.',
    },
  };

  String get(String key, {Map<String, String>? params}) {
    String value = _localizedValues[locale]?[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}
