title: Caravella - Group Expense & Travel Manager
description: Modern app for managing group expenses, trips, and participants. Ideal for group travel, roommates, and events.
remote_theme: home-assistant/home-assistant.io
