name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      # - name: Run tests
      #   run: flutter test
      - name: Build release APK
        run: flutter build apk --release
      - name: Get app version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/\+.*//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk org_app_caravella-${{ env.VERSION }}-${{ env.DATE }}.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: org_app_caravella-apk
          path: org_app_caravella-*.apk

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build release APK
        run: flutter build apk --release
      - name: Get app version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/\+.*//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk org_app_caravella-${{ env.VERSION }}-${{ env.DATE }}.apk
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: org_app_caravella-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
