name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build release APK
        run: flutter build apk --release
      - name: Get app version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/\+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk org_app_split-${{ steps.get_version.outputs.version }}-${{ steps.get_date.outputs.date }}.apk
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: org_app_split-*.apk
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build release APK
        run: flutter build apk --release
      - name: Get app version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //;s/\+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk org_app_split-${{ steps.get_version.outputs.version }}-${{ steps.get_date.outputs.date }}.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: org_app_split-apk
          path: org_app_split-*.apk
